### ISSUE TITLE
Comman 'mount' failed with exit status 32

### ISSUE THREAD

**Issue by mattisengstedt** [bswebdk/x2pinn#1]
Hi!

First of, love your script, thanks to I can multiboot batocera.

I´m trying to convert Dosbian 2.5 to pinn format.
https://cmaiolino.wordpress.com/dosbian/

Running the script I can successfully process partition 1 but when mounting partition 2 I get
"mount: /home/....../dosbian/mnt: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
Comman 'mount' failed with exit status 32"

Any ideas for what I can try?

**Comment by mattisengstedt** [comment]
To add on, running dmesg gave me

'bad geometry: block count 1367808 exceeds size of device (1367807 blocks)'

**Comment by bswebdk** [comment]
Thank you for the thumbs up! :)

Your problem has nothing to do with x2pinn, the second partition in the image file is one block too short and this is something the image provider (dosbian author) should fix.

**Comment by mattisengstedt** [comment]
I flashed the image to a usb stick and used that instead, that got me a bit further but it failed when compressing the tar to xz instead.

The first partition succeeds but the secondone fails during tarball creation.

'Comman 'bsdtar' failed with exit status 1'
